name: flutter_magento_ui
description: Reusable UI widgets for Magento Flutter apps
version: 2.0.0
repository: https://github.com/nativemind/flutter_magento
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_magento_core:
    path: ../flutter_magento_core
  flutter_magento_localizations:
    path: ../flutter_magento_localizations
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
