name: flutter_magento_ui
description: UI components for Flutter Magento SDK - product cards, cart widgets, theme.
version: 1.0.0
homepage: https://github.com/libsMagento/flutter_magento
repository: https://github.com/libsMagento/flutter_magento/tree/main/packages/flutter_magento_ui
issue_tracker: https://github.com/libsMagento/flutter_magento/issues

topics:
  - magento
  - ecommerce
  - ui

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_magento_core: ^1.0.0
  flutter_magento_localizations: ^1.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
