// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Magento configuration data
///
/// Generated class from Pigeon that represents data sent in messages.
struct MagentoConfiguration: Hashable {
  var baseUrl: String
  var headers: [String: String]? = nil
  var connectionTimeout: Int64? = nil
  var receiveTimeout: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MagentoConfiguration? {
    let baseUrl = pigeonVar_list[0] as! String
    let headers: [String: String]? = nilOrValue(pigeonVar_list[1])
    let connectionTimeout: Int64? = nilOrValue(pigeonVar_list[2])
    let receiveTimeout: Int64? = nilOrValue(pigeonVar_list[3])

    return MagentoConfiguration(
      baseUrl: baseUrl,
      headers: headers,
      connectionTimeout: connectionTimeout,
      receiveTimeout: receiveTimeout
    )
  }
  func toList() -> [Any?] {
    return [
      baseUrl,
      headers,
      connectionTimeout,
      receiveTimeout,
    ]
  }
  static func == (lhs: MagentoConfiguration, rhs: MagentoConfiguration) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Customer credentials for authentication
///
/// Generated class from Pigeon that represents data sent in messages.
struct CustomerCredentials: Hashable {
  var email: String
  var password: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CustomerCredentials? {
    let email = pigeonVar_list[0] as! String
    let password = pigeonVar_list[1] as! String

    return CustomerCredentials(
      email: email,
      password: password
    )
  }
  func toList() -> [Any?] {
    return [
      email,
      password,
    ]
  }
  static func == (lhs: CustomerCredentials, rhs: CustomerCredentials) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Customer data for registration
///
/// Generated class from Pigeon that represents data sent in messages.
struct CustomerData: Hashable {
  var email: String
  var password: String
  var firstName: String
  var lastName: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CustomerData? {
    let email = pigeonVar_list[0] as! String
    let password = pigeonVar_list[1] as! String
    let firstName = pigeonVar_list[2] as! String
    let lastName = pigeonVar_list[3] as! String

    return CustomerData(
      email: email,
      password: password,
      firstName: firstName,
      lastName: lastName
    )
  }
  func toList() -> [Any?] {
    return [
      email,
      password,
      firstName,
      lastName,
    ]
  }
  static func == (lhs: CustomerData, rhs: CustomerData) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Customer information
///
/// Generated class from Pigeon that represents data sent in messages.
struct Customer: Hashable {
  var id: String
  var email: String
  var firstName: String
  var lastName: String
  var phone: String? = nil
  var dateOfBirth: String? = nil
  var gender: Int64? = nil
  var customAttributes: [String: dynamic]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Customer? {
    let id = pigeonVar_list[0] as! String
    let email = pigeonVar_list[1] as! String
    let firstName = pigeonVar_list[2] as! String
    let lastName = pigeonVar_list[3] as! String
    let phone: String? = nilOrValue(pigeonVar_list[4])
    let dateOfBirth: String? = nilOrValue(pigeonVar_list[5])
    let gender: Int64? = nilOrValue(pigeonVar_list[6])
    let customAttributes: [String: dynamic]? = nilOrValue(pigeonVar_list[7])

    return Customer(
      id: id,
      email: email,
      firstName: firstName,
      lastName: lastName,
      phone: phone,
      dateOfBirth: dateOfBirth,
      gender: gender,
      customAttributes: customAttributes
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      email,
      firstName,
      lastName,
      phone,
      dateOfBirth,
      gender,
      customAttributes,
    ]
  }
  static func == (lhs: Customer, rhs: Customer) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Product request parameters
///
/// Generated class from Pigeon that represents data sent in messages.
struct ProductRequest: Hashable {
  var page: Int64
  var pageSize: Int64
  var searchQuery: String? = nil
  var categoryId: String? = nil
  var sortBy: String? = nil
  var sortOrder: String? = nil
  var filters: [String: dynamic]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProductRequest? {
    let page = pigeonVar_list[0] as! Int64
    let pageSize = pigeonVar_list[1] as! Int64
    let searchQuery: String? = nilOrValue(pigeonVar_list[2])
    let categoryId: String? = nilOrValue(pigeonVar_list[3])
    let sortBy: String? = nilOrValue(pigeonVar_list[4])
    let sortOrder: String? = nilOrValue(pigeonVar_list[5])
    let filters: [String: dynamic]? = nilOrValue(pigeonVar_list[6])

    return ProductRequest(
      page: page,
      pageSize: pageSize,
      searchQuery: searchQuery,
      categoryId: categoryId,
      sortBy: sortBy,
      sortOrder: sortOrder,
      filters: filters
    )
  }
  func toList() -> [Any?] {
    return [
      page,
      pageSize,
      searchQuery,
      categoryId,
      sortBy,
      sortOrder,
      filters,
    ]
  }
  static func == (lhs: ProductRequest, rhs: ProductRequest) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Product information
///
/// Generated class from Pigeon that represents data sent in messages.
struct Product: Hashable {
  var sku: String
  var name: String
  var price: Double
  var description: String? = nil
  var shortDescription: String? = nil
  var images: [String]? = nil
  var customAttributes: [String: dynamic]? = nil
  var stockStatus: String? = nil
  var quantity: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Product? {
    let sku = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let price = pigeonVar_list[2] as! Double
    let description: String? = nilOrValue(pigeonVar_list[3])
    let shortDescription: String? = nilOrValue(pigeonVar_list[4])
    let images: [String]? = nilOrValue(pigeonVar_list[5])
    let customAttributes: [String: dynamic]? = nilOrValue(pigeonVar_list[6])
    let stockStatus: String? = nilOrValue(pigeonVar_list[7])
    let quantity: Int64? = nilOrValue(pigeonVar_list[8])

    return Product(
      sku: sku,
      name: name,
      price: price,
      description: description,
      shortDescription: shortDescription,
      images: images,
      customAttributes: customAttributes,
      stockStatus: stockStatus,
      quantity: quantity
    )
  }
  func toList() -> [Any?] {
    return [
      sku,
      name,
      price,
      description,
      shortDescription,
      images,
      customAttributes,
      stockStatus,
      quantity,
    ]
  }
  static func == (lhs: Product, rhs: Product) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Product list with pagination
///
/// Generated class from Pigeon that represents data sent in messages.
struct ProductList: Hashable {
  var items: [Product]
  var totalCount: Int64
  var pageSize: Int64
  var currentPage: Int64
  var totalPages: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProductList? {
    let items = pigeonVar_list[0] as! [Product]
    let totalCount = pigeonVar_list[1] as! Int64
    let pageSize = pigeonVar_list[2] as! Int64
    let currentPage = pigeonVar_list[3] as! Int64
    let totalPages = pigeonVar_list[4] as! Int64

    return ProductList(
      items: items,
      totalCount: totalCount,
      pageSize: pageSize,
      currentPage: currentPage,
      totalPages: totalPages
    )
  }
  func toList() -> [Any?] {
    return [
      items,
      totalCount,
      pageSize,
      currentPage,
      totalPages,
    ]
  }
  static func == (lhs: ProductList, rhs: ProductList) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Cart item
///
/// Generated class from Pigeon that represents data sent in messages.
struct CartItem: Hashable {
  var sku: String
  var quantity: Int64
  var productOptions: [String: dynamic]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CartItem? {
    let sku = pigeonVar_list[0] as! String
    let quantity = pigeonVar_list[1] as! Int64
    let productOptions: [String: dynamic]? = nilOrValue(pigeonVar_list[2])

    return CartItem(
      sku: sku,
      quantity: quantity,
      productOptions: productOptions
    )
  }
  func toList() -> [Any?] {
    return [
      sku,
      quantity,
      productOptions,
    ]
  }
  static func == (lhs: CartItem, rhs: CartItem) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Shopping cart
///
/// Generated class from Pigeon that represents data sent in messages.
struct Cart: Hashable {
  var id: String
  var items: [CartItem]
  var itemsCount: Int64
  var itemsQty: Int64
  var grandTotal: Double
  var subtotal: Double? = nil
  var taxAmount: Double? = nil
  var discountAmount: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Cart? {
    let id = pigeonVar_list[0] as! String
    let items = pigeonVar_list[1] as! [CartItem]
    let itemsCount = pigeonVar_list[2] as! Int64
    let itemsQty = pigeonVar_list[3] as! Int64
    let grandTotal = pigeonVar_list[4] as! Double
    let subtotal: Double? = nilOrValue(pigeonVar_list[5])
    let taxAmount: Double? = nilOrValue(pigeonVar_list[6])
    let discountAmount: Double? = nilOrValue(pigeonVar_list[7])

    return Cart(
      id: id,
      items: items,
      itemsCount: itemsCount,
      itemsQty: itemsQty,
      grandTotal: grandTotal,
      subtotal: subtotal,
      taxAmount: taxAmount,
      discountAmount: discountAmount
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      items,
      itemsCount,
      itemsQty,
      grandTotal,
      subtotal,
      taxAmount,
      discountAmount,
    ]
  }
  static func == (lhs: Cart, rhs: Cart) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Order information
///
/// Generated class from Pigeon that represents data sent in messages.
struct Order: Hashable {
  var id: String
  var incrementId: String
  var status: String
  var state: String
  var grandTotal: Double
  var createdAt: String
  var items: [CartItem]? = nil
  var billingAddress: [String: dynamic]? = nil
  var shippingAddress: [String: dynamic]? = nil
  var paymentMethod: String? = nil
  var shippingMethod: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Order? {
    let id = pigeonVar_list[0] as! String
    let incrementId = pigeonVar_list[1] as! String
    let status = pigeonVar_list[2] as! String
    let state = pigeonVar_list[3] as! String
    let grandTotal = pigeonVar_list[4] as! Double
    let createdAt = pigeonVar_list[5] as! String
    let items: [CartItem]? = nilOrValue(pigeonVar_list[6])
    let billingAddress: [String: dynamic]? = nilOrValue(pigeonVar_list[7])
    let shippingAddress: [String: dynamic]? = nilOrValue(pigeonVar_list[8])
    let paymentMethod: String? = nilOrValue(pigeonVar_list[9])
    let shippingMethod: String? = nilOrValue(pigeonVar_list[10])

    return Order(
      id: id,
      incrementId: incrementId,
      status: status,
      state: state,
      grandTotal: grandTotal,
      createdAt: createdAt,
      items: items,
      billingAddress: billingAddress,
      shippingAddress: shippingAddress,
      paymentMethod: paymentMethod,
      shippingMethod: shippingMethod
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      incrementId,
      status,
      state,
      grandTotal,
      createdAt,
      items,
      billingAddress,
      shippingAddress,
      paymentMethod,
      shippingMethod,
    ]
  }
  static func == (lhs: Order, rhs: Order) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

/// Wishlist information
///
/// Generated class from Pigeon that represents data sent in messages.
struct Wishlist: Hashable {
  var id: String
  var items: [Product]
  var itemsCount: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> Wishlist? {
    let id = pigeonVar_list[0] as! String
    let items = pigeonVar_list[1] as! [Product]
    let itemsCount = pigeonVar_list[2] as! Int64

    return Wishlist(
      id: id,
      items: items,
      itemsCount: itemsCount
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      items,
      itemsCount,
    ]
  }
  static func == (lhs: Wishlist, rhs: Wishlist) -> Bool {
    return deepEqualsApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashApi(value: toList(), hasher: &hasher)
  }
}

private class ApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return MagentoConfiguration.fromList(self.readValue() as! [Any?])
    case 130:
      return CustomerCredentials.fromList(self.readValue() as! [Any?])
    case 131:
      return CustomerData.fromList(self.readValue() as! [Any?])
    case 132:
      return Customer.fromList(self.readValue() as! [Any?])
    case 133:
      return ProductRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return Product.fromList(self.readValue() as! [Any?])
    case 135:
      return ProductList.fromList(self.readValue() as! [Any?])
    case 136:
      return CartItem.fromList(self.readValue() as! [Any?])
    case 137:
      return Cart.fromList(self.readValue() as! [Any?])
    case 138:
      return Order.fromList(self.readValue() as! [Any?])
    case 139:
      return Wishlist.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MagentoConfiguration {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CustomerCredentials {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CustomerData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? Customer {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ProductRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? Product {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ProductList {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? CartItem {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? Cart {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? Order {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? Wishlist {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ApiPigeonCodecWriter(data: data)
  }
}

class ApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ApiPigeonCodec(readerWriter: ApiPigeonCodecReaderWriter())
}

