name: flutter_magento_core
description: Core abstractions for Flutter Magento SDK - transport, repositories, models, errors.
version: 1.0.0
homepage: https://github.com/libsMagento/flutter_magento
repository: https://github.com/libsMagento/flutter_magento/tree/main/packages/flutter_magento_core
issue_tracker: https://github.com/libsMagento/flutter_magento/issues

topics:
  - magento
  - ecommerce
  - sdk

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
