name: flutter_magento_graphql
description: GraphQL transport implementation for flutter_magento SDK.
version: 0.0.1
homepage: https://github.com/nativemind/flutter_magento
publish_to: none

environment:
  sdk: ^3.11.5

dependencies:
  flutter_magento_core:
    path: ../flutter_magento_core
  gql: ^1.0.1
  gql_http_link: ^1.0.1
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
