// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_magento/test/examples/auth_examples_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:flutter_magento/src/flutter_magento_core.dart' as _i6;
import 'package:flutter_magento/src/models/cart_models.dart' as _i8;
import 'package:flutter_magento/src/models/customer_models.dart' as _i5;
import 'package:flutter_magento/src/preload_data/preload_data_provider.dart'
    as _i9;
import 'package:flutter_magento/src/services/auth_service.dart' as _i3;
import 'package:flutter_magento/src/services/cart_service.dart' as _i4;
import 'package:flutter_magento/src/services/magento_api_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMagentoApiService_0 extends _i1.SmartFake
    implements _i2.MagentoApiService {
  _FakeMagentoApiService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_1 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartService_2 extends _i1.SmartFake implements _i4.CartService {
  _FakeCartService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomer_3 extends _i1.SmartFake implements _i5.Customer {
  _FakeCustomer_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FlutterMagentoCore].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterMagentoCore extends _i1.Mock
    implements _i6.FlutterMagentoCore {
  MockFlutterMagentoCore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MagentoApiService get apiService =>
      (super.noSuchMethod(
            Invocation.getter(#apiService),
            returnValue: _FakeMagentoApiService_0(
              this,
              Invocation.getter(#apiService),
            ),
          )
          as _i2.MagentoApiService);

  @override
  _i3.AuthService get authService =>
      (super.noSuchMethod(
            Invocation.getter(#authService),
            returnValue: _FakeAuthService_1(
              this,
              Invocation.getter(#authService),
            ),
          )
          as _i3.AuthService);

  @override
  _i4.CartService get cartService =>
      (super.noSuchMethod(
            Invocation.getter(#cartService),
            returnValue: _FakeCartService_2(
              this,
              Invocation.getter(#cartService),
            ),
          )
          as _i4.CartService);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  int get cartItemsCount =>
      (super.noSuchMethod(Invocation.getter(#cartItemsCount), returnValue: 0)
          as int);

  @override
  double get cartTotal =>
      (super.noSuchMethod(Invocation.getter(#cartTotal), returnValue: 0.0)
          as double);

  @override
  bool get isCartEmpty =>
      (super.noSuchMethod(Invocation.getter(#isCartEmpty), returnValue: false)
          as bool);

  @override
  String get version =>
      (super.noSuchMethod(
            Invocation.getter(#version),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#version),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  List<dynamic> getPreloadProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getPreloadProducts, []),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<dynamic> getPreloadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getPreloadCategories, []),
            returnValue: <dynamic>[],
          )
          as List<dynamic>);

  @override
  List<_i8.CartItem> getPreloadCartItems() =>
      (super.noSuchMethod(
            Invocation.method(#getPreloadCartItems, []),
            returnValue: <_i8.CartItem>[],
          )
          as List<_i8.CartItem>);

  @override
  void registerPreloadDataProvider(
    String? name,
    _i9.PreloadDataProvider? provider,
  ) => super.noSuchMethod(
    Invocation.method(#registerPreloadDataProvider, [name, provider]),
    returnValueForMissingStub: null,
  );

  @override
  void setPreloadDataProvider(String? name) => super.noSuchMethod(
    Invocation.method(#setPreloadDataProvider, [name]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getPreloadDataProviderInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getPreloadDataProviderInfo, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i10.Future<bool> initialize({
    required String? baseUrl,
    Map<String, String>? headers,
    int? connectionTimeout = 30000,
    int? receiveTimeout = 30000,
    String? adminToken,
    bool? enableCaching = true,
    bool? enableRateLimiting = true,
    _i9.PreloadDataProvider? preloadDataProvider,
    bool? enablePreloadData = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #baseUrl: baseUrl,
              #headers: headers,
              #connectionTimeout: connectionTimeout,
              #receiveTimeout: receiveTimeout,
              #adminToken: adminToken,
              #enableCaching: enableCaching,
              #enableRateLimiting: enableRateLimiting,
              #preloadDataProvider: preloadDataProvider,
              #enablePreloadData: enablePreloadData,
            }),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<dynamic> authenticate({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#authenticate, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<dynamic> createAccount({
    required String? email,
    required String? password,
    required String? firstName,
    required String? lastName,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #email: email,
              #password: password,
              #firstName: firstName,
              #lastName: lastName,
              #additionalData: additionalData,
            }),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<_i5.Customer> getCustomer() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomer, []),
            returnValue: _i10.Future<_i5.Customer>.value(
              _FakeCustomer_3(this, Invocation.method(#getCustomer, [])),
            ),
          )
          as _i10.Future<_i5.Customer>);

  @override
  _i10.Future<Map<String, dynamic>> getProducts({
    int? page = 1,
    int? pageSize = 20,
    String? searchQuery,
    String? categoryId,
    String? sortBy,
    String? sortOrder,
    Map<String, dynamic>? filters,
    bool? useGraphQL = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #page: page,
              #pageSize: pageSize,
              #searchQuery: searchQuery,
              #categoryId: categoryId,
              #sortBy: sortBy,
              #sortOrder: sortOrder,
              #filters: filters,
              #useGraphQL: useGraphQL,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<dynamic> getProduct(String? sku, {bool? useGraphQL = true}) =>
      (super.noSuchMethod(
            Invocation.method(#getProduct, [sku], {#useGraphQL: useGraphQL}),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<Map<String, dynamic>> searchProducts(
    String? query, {
    int? page = 1,
    int? pageSize = 20,
    bool? useGraphQL = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchProducts,
              [query],
              {#page: page, #pageSize: pageSize, #useGraphQL: useGraphQL},
            ),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getCategories({
    bool? useGraphQL = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [], {#useGraphQL: useGraphQL}),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>> getCategory(int? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getCategory, [categoryId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getProductsByCategory(
    String? categoryId, {
    int? page = 1,
    int? pageSize = 20,
    String? sortBy,
    String? sortOrder,
    bool? useGraphQL = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProductsByCategory,
              [categoryId],
              {
                #page: page,
                #pageSize: pageSize,
                #sortBy: sortBy,
                #sortOrder: sortOrder,
                #useGraphQL: useGraphQL,
              },
            ),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<String> createCart() =>
      (super.noSuchMethod(
            Invocation.method(#createCart, []),
            returnValue: _i10.Future<String>.value(
              _i7.dummyValue<String>(this, Invocation.method(#createCart, [])),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<dynamic> getCart() =>
      (super.noSuchMethod(
            Invocation.method(#getCart, []),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<bool> addToCart({
    required String? sku,
    required int? quantity,
    Map<String, dynamic>? productOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [], {
              #sku: sku,
              #quantity: quantity,
              #productOptions: productOptions,
            }),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> updateCartItemQuantity({
    required int? itemId,
    required int? quantity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateCartItemQuantity, [], {
              #itemId: itemId,
              #quantity: quantity,
            }),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> removeFromCart(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [itemId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<dynamic>> getCustomerOrders() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerOrders, []),
            returnValue: _i10.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i10.Future<List<dynamic>>);

  @override
  _i10.Future<dynamic> getOrder(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#getOrder, [orderId]),
            returnValue: _i10.Future<dynamic>.value(),
          )
          as _i10.Future<dynamic>);

  @override
  _i10.Future<Map<String, dynamic>> getWishlist() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlist, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<bool> addToWishlist(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#addToWishlist, [sku]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> removeFromWishlist(int? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWishlist, [itemId]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<List<Map<String, dynamic>>> estimateShipping(
    Map<String, dynamic>? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#estimateShipping, [address]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getPaymentMethods() =>
      (super.noSuchMethod(
            Invocation.method(#getPaymentMethods, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>> placeOrder(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#placeOrder, [orderData]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  bool isProductInCart(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#isProductInCart, [sku]),
            returnValue: false,
          )
          as bool);

  @override
  int getProductQuantityInCart(String? sku) =>
      (super.noSuchMethod(
            Invocation.method(#getProductQuantityInCart, [sku]),
            returnValue: 0,
          )
          as int);

  @override
  _i10.Future<bool> applyCoupon(String? couponCode) =>
      (super.noSuchMethod(
            Invocation.method(#applyCoupon, [couponCode]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<bool> removeCoupon() =>
      (super.noSuchMethod(
            Invocation.method(#removeCoupon, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> getStoreConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getStoreConfig, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getCurrency() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrency, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getCmsPages() =>
      (super.noSuchMethod(
            Invocation.method(#getCmsPages, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>?> executeGraphQL(
    String? query, {
    Map<String, dynamic>? variables,
    String? operationName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeGraphQL,
              [query],
              {#variables: variables, #operationName: operationName},
            ),
            returnValue: _i10.Future<Map<String, dynamic>?>.value(),
          )
          as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<bool> isGraphQLAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isGraphQLAvailable, []),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<Map<String, dynamic>> getCategoryTree({
    int? rootCategoryId = 2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCategoryTree, [], {
              #rootCategoryId: rootCategoryId,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getProductReviews(
    String? sku, {
    int? page = 1,
    int? pageSize = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getProductReviews,
              [sku],
              {#page: page, #pageSize: pageSize},
            ),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getProductFilters({String? categoryId}) =>
      (super.noSuchMethod(
            Invocation.method(#getProductFilters, [], {
              #categoryId: categoryId,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getWishlistGraphQL() =>
      (super.noSuchMethod(
            Invocation.method(#getWishlistGraphQL, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getCustomerOrdersGraphQL({
    int? page = 1,
    int? pageSize = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerOrdersGraphQL, [], {
              #page: page,
              #pageSize: pageSize,
            }),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<Map<String, dynamic>> getCustomerInfoGraphQL() =>
      (super.noSuchMethod(
            Invocation.method(#getCustomerInfoGraphQL, []),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getProductRecommendations(
    String? sku,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductRecommendations, [sku]),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getCountries() =>
      (super.noSuchMethod(
            Invocation.method(#getCountries, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<Map<String, dynamic>> getSearchSuggestions(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchSuggestions, [query]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);
}
