// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package ru.nativemind.flutter.magento.flutter_magento

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ApiPigeonUtils {
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * Magento configuration data
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MagentoConfiguration (
  val baseUrl: String,
  val headers: Map<String, String>? = null,
  val connectionTimeout: Long? = null,
  val receiveTimeout: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MagentoConfiguration {
      val baseUrl = pigeonVar_list[0] as String
      val headers = pigeonVar_list[1] as Map<String, String>?
      val connectionTimeout = pigeonVar_list[2] as Long?
      val receiveTimeout = pigeonVar_list[3] as Long?
      return MagentoConfiguration(baseUrl, headers, connectionTimeout, receiveTimeout)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      baseUrl,
      headers,
      connectionTimeout,
      receiveTimeout,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is MagentoConfiguration) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Customer credentials for authentication
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CustomerCredentials (
  val email: String,
  val password: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CustomerCredentials {
      val email = pigeonVar_list[0] as String
      val password = pigeonVar_list[1] as String
      return CustomerCredentials(email, password)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      email,
      password,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CustomerCredentials) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Customer data for registration
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CustomerData (
  val email: String,
  val password: String,
  val firstName: String,
  val lastName: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CustomerData {
      val email = pigeonVar_list[0] as String
      val password = pigeonVar_list[1] as String
      val firstName = pigeonVar_list[2] as String
      val lastName = pigeonVar_list[3] as String
      return CustomerData(email, password, firstName, lastName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      email,
      password,
      firstName,
      lastName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CustomerData) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Customer information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Customer (
  val id: String,
  val email: String,
  val firstName: String,
  val lastName: String,
  val phone: String? = null,
  val dateOfBirth: String? = null,
  val gender: Long? = null,
  val customAttributes: Map<String, dynamic>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Customer {
      val id = pigeonVar_list[0] as String
      val email = pigeonVar_list[1] as String
      val firstName = pigeonVar_list[2] as String
      val lastName = pigeonVar_list[3] as String
      val phone = pigeonVar_list[4] as String?
      val dateOfBirth = pigeonVar_list[5] as String?
      val gender = pigeonVar_list[6] as Long?
      val customAttributes = pigeonVar_list[7] as Map<String, dynamic>?
      return Customer(id, email, firstName, lastName, phone, dateOfBirth, gender, customAttributes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      email,
      firstName,
      lastName,
      phone,
      dateOfBirth,
      gender,
      customAttributes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Customer) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Product request parameters
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProductRequest (
  val page: Long,
  val pageSize: Long,
  val searchQuery: String? = null,
  val categoryId: String? = null,
  val sortBy: String? = null,
  val sortOrder: String? = null,
  val filters: Map<String, dynamic>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProductRequest {
      val page = pigeonVar_list[0] as Long
      val pageSize = pigeonVar_list[1] as Long
      val searchQuery = pigeonVar_list[2] as String?
      val categoryId = pigeonVar_list[3] as String?
      val sortBy = pigeonVar_list[4] as String?
      val sortOrder = pigeonVar_list[5] as String?
      val filters = pigeonVar_list[6] as Map<String, dynamic>?
      return ProductRequest(page, pageSize, searchQuery, categoryId, sortBy, sortOrder, filters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      page,
      pageSize,
      searchQuery,
      categoryId,
      sortBy,
      sortOrder,
      filters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ProductRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Product information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Product (
  val sku: String,
  val name: String,
  val price: Double,
  val description: String? = null,
  val shortDescription: String? = null,
  val images: List<String>? = null,
  val customAttributes: Map<String, dynamic>? = null,
  val stockStatus: String? = null,
  val quantity: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Product {
      val sku = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val price = pigeonVar_list[2] as Double
      val description = pigeonVar_list[3] as String?
      val shortDescription = pigeonVar_list[4] as String?
      val images = pigeonVar_list[5] as List<String>?
      val customAttributes = pigeonVar_list[6] as Map<String, dynamic>?
      val stockStatus = pigeonVar_list[7] as String?
      val quantity = pigeonVar_list[8] as Long?
      return Product(sku, name, price, description, shortDescription, images, customAttributes, stockStatus, quantity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sku,
      name,
      price,
      description,
      shortDescription,
      images,
      customAttributes,
      stockStatus,
      quantity,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Product) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Product list with pagination
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class ProductList (
  val items: List<Product>,
  val totalCount: Long,
  val pageSize: Long,
  val currentPage: Long,
  val totalPages: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ProductList {
      val items = pigeonVar_list[0] as List<Product>
      val totalCount = pigeonVar_list[1] as Long
      val pageSize = pigeonVar_list[2] as Long
      val currentPage = pigeonVar_list[3] as Long
      val totalPages = pigeonVar_list[4] as Long
      return ProductList(items, totalCount, pageSize, currentPage, totalPages)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      items,
      totalCount,
      pageSize,
      currentPage,
      totalPages,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ProductList) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Cart item
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class CartItem (
  val sku: String,
  val quantity: Long,
  val productOptions: Map<String, dynamic>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CartItem {
      val sku = pigeonVar_list[0] as String
      val quantity = pigeonVar_list[1] as Long
      val productOptions = pigeonVar_list[2] as Map<String, dynamic>?
      return CartItem(sku, quantity, productOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sku,
      quantity,
      productOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is CartItem) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Shopping cart
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Cart (
  val id: String,
  val items: List<CartItem>,
  val itemsCount: Long,
  val itemsQty: Long,
  val grandTotal: Double,
  val subtotal: Double? = null,
  val taxAmount: Double? = null,
  val discountAmount: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Cart {
      val id = pigeonVar_list[0] as String
      val items = pigeonVar_list[1] as List<CartItem>
      val itemsCount = pigeonVar_list[2] as Long
      val itemsQty = pigeonVar_list[3] as Long
      val grandTotal = pigeonVar_list[4] as Double
      val subtotal = pigeonVar_list[5] as Double?
      val taxAmount = pigeonVar_list[6] as Double?
      val discountAmount = pigeonVar_list[7] as Double?
      return Cart(id, items, itemsCount, itemsQty, grandTotal, subtotal, taxAmount, discountAmount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      items,
      itemsCount,
      itemsQty,
      grandTotal,
      subtotal,
      taxAmount,
      discountAmount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Cart) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Order information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Order (
  val id: String,
  val incrementId: String,
  val status: String,
  val state: String,
  val grandTotal: Double,
  val createdAt: String,
  val items: List<CartItem>? = null,
  val billingAddress: Map<String, dynamic>? = null,
  val shippingAddress: Map<String, dynamic>? = null,
  val paymentMethod: String? = null,
  val shippingMethod: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Order {
      val id = pigeonVar_list[0] as String
      val incrementId = pigeonVar_list[1] as String
      val status = pigeonVar_list[2] as String
      val state = pigeonVar_list[3] as String
      val grandTotal = pigeonVar_list[4] as Double
      val createdAt = pigeonVar_list[5] as String
      val items = pigeonVar_list[6] as List<CartItem>?
      val billingAddress = pigeonVar_list[7] as Map<String, dynamic>?
      val shippingAddress = pigeonVar_list[8] as Map<String, dynamic>?
      val paymentMethod = pigeonVar_list[9] as String?
      val shippingMethod = pigeonVar_list[10] as String?
      return Order(id, incrementId, status, state, grandTotal, createdAt, items, billingAddress, shippingAddress, paymentMethod, shippingMethod)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      incrementId,
      status,
      state,
      grandTotal,
      createdAt,
      items,
      billingAddress,
      shippingAddress,
      paymentMethod,
      shippingMethod,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Order) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Wishlist information
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class Wishlist (
  val id: String,
  val items: List<Product>,
  val itemsCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Wishlist {
      val id = pigeonVar_list[0] as String
      val items = pigeonVar_list[1] as List<Product>
      val itemsCount = pigeonVar_list[2] as Long
      return Wishlist(id, items, itemsCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      items,
      itemsCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Wishlist) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MagentoConfiguration.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CustomerCredentials.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CustomerData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Customer.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProductRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Product.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ProductList.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CartItem.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Cart.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Order.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Wishlist.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MagentoConfiguration -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is CustomerCredentials -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is CustomerData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is Customer -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ProductRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is Product -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ProductList -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is CartItem -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is Cart -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is Order -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is Wishlist -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

