name: flutter_magento_riverpod
description: Riverpod providers and state management for Flutter Magento SDK.
version: 1.0.0
homepage: https://github.com/libsMagento/flutter_magento
repository: https://github.com/libsMagento/flutter_magento/tree/main/packages/flutter_magento_riverpod
issue_tracker: https://github.com/libsMagento/flutter_magento/issues

topics:
  - magento
  - ecommerce
  - riverpod

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_magento_core: ^1.0.0
  flutter_magento_auth: ^1.0.0
  flutter_magento_catalog: ^1.0.0
  flutter_magento_cart: ^1.0.0
  flutter_magento_profile: ^1.0.0
  flutter_riverpod: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
