name: flutter_magento_blockchain
description: Blockchain integrations for Flutter Magento SDK - ICP payments, NFT products, Yuku.
version: 1.0.0
homepage: https://github.com/libsMagento/flutter_magento
repository: https://github.com/libsMagento/flutter_magento/tree/main/packages/flutter_magento_blockchain
issue_tracker: https://github.com/libsMagento/flutter_magento/issues

topics:
  - magento
  - ecommerce
  - blockchain

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_magento_core: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
