import '../context/magento_store_context.dart';
import 'magento_route_type.dart';

/// Route payload from Magento's flutter-magento-route metadata.
///
/// This is the Dart-side parser for the flutter_magento_v1 standard
/// generated by NativeMind_BridgeRoutes.
///
/// Example JSON:
/// ```json
/// {
///   "standard": "flutter_magento_v1",
///   "type": "product",
///   "canonicalUrl": "https://shop.com/driven-backpack.html",
///   "sourceUrl": "https://shop.com/bags/driven-backpack.html?utm=x",
///   "webPath": "/driven-backpack.html",
///   "appRoute": "/product/123",
///   "entity": {"id": 123, "sku": "24-WB03", "urlKey": "driven-backpack"},
///   "store": {"websiteCode": "base", "storeCode": "default", "currency": "USD"}
/// }
/// ```
class MagentoRoutePayload {
  /// Standard version identifier (e.g., "flutter_magento_v1")
  final String standard;

  /// Route type
  final MagentoRouteType type;

  /// Canonical URL - the normalized, SEO-friendly URL
  final Uri canonicalUrl;

  /// Source URL - the actual request URL (may include tracking params)
  /// Null if same as canonicalUrl
  final Uri? sourceUrl;

  /// Web path portion of the canonical URL
  final String webPath;

  /// App route for Flutter navigation
  final String appRoute;

  /// Entity-specific data (product id/sku, category id, etc.)
  final Map<String, Object?> entity;

  /// Store context
  final MagentoStoreContext? store;

  const MagentoRoutePayload({
    required this.standard,
    required this.type,
    required this.canonicalUrl,
    this.sourceUrl,
    required this.webPath,
    required this.appRoute,
    this.entity = const {},
    this.store,
  });

  /// Parse from JSON (flutter-magento-route script content)
  factory MagentoRoutePayload.fromJson(Map<String, dynamic> json) {
    final storeData = json['store'] as Map<String, dynamic>?;

    return MagentoRoutePayload(
      standard: json['standard'] as String? ?? 'flutter_magento_v1',
      type: MagentoRouteType.fromString(json['type'] as String?),
      canonicalUrl: Uri.parse(json['canonicalUrl'] as String? ?? ''),
      sourceUrl: json['sourceUrl'] != null
          ? Uri.parse(json['sourceUrl'] as String)
          : null,
      webPath: json['webPath'] as String? ?? '',
      appRoute: json['appRoute'] as String? ?? '/',
      entity: (json['entity'] as Map<String, dynamic>?) ?? const {},
      store: storeData != null
          ? MagentoStoreContext(
              websiteCode: storeData['websiteCode'] as String?,
              storeCode: storeData['storeCode'] as String? ?? 'default',
              currency: storeData['currency'] as String? ?? 'USD',
              locale: storeData['locale'] as String? ?? 'en_US',
            )
          : null,
    );
  }

  /// Get the effective URL (sourceUrl if available, otherwise canonicalUrl)
  Uri get effectiveUrl => sourceUrl ?? canonicalUrl;

  /// Check if sourceUrl differs from canonicalUrl
  bool get hasAlternateSource =>
      sourceUrl != null && sourceUrl.toString() != canonicalUrl.toString();

  /// Get entity value by key with type casting
  T? entityValue<T>(String key) {
    final value = entity[key];
    if (value is T) return value;
    return null;
  }

  /// Product-specific: get product ID
  int? get productId => entityValue<int>('id');

  /// Product-specific: get product SKU
  String? get productSku => entityValue<String>('sku');

  /// Product-specific: get product URL key
  String? get productUrlKey => entityValue<String>('urlKey');

  /// Category-specific: get category ID
  int? get categoryId => entityValue<int>('id');

  /// Category-specific: get category URL path
  String? get categoryUrlPath => entityValue<String>('urlPath');

  /// CMS-specific: get page identifier
  String? get cmsIdentifier => entityValue<String>('identifier');

  /// Search-specific: get search query
  String? get searchQuery => entityValue<String>('query');

  /// Convert to JSON
  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{
      'standard': standard,
      'type': type.name,
      'canonicalUrl': canonicalUrl.toString(),
      'webPath': webPath,
      'appRoute': appRoute,
      'entity': entity,
    };

    if (sourceUrl != null) {
      json['sourceUrl'] = sourceUrl.toString();
    }

    if (store != null) {
      json['store'] = {
        'websiteCode': store!.websiteCode,
        'storeCode': store!.storeCode,
        'currency': store!.currency,
        'locale': store!.locale,
      };
    }

    return json;
  }

  @override
  String toString() =>
      'MagentoRoutePayload(type: $type, appRoute: $appRoute, canonical: $canonicalUrl)';
}
