name: flutter_magento_riverpod
description: Riverpod providers and controllers for Magento Flutter apps
version: 2.0.0
repository: https://github.com/nativemind/flutter_magento
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_magento_core:
    path: ../flutter_magento_core
  flutter_magento_auth:
    path: ../flutter_magento_auth
  flutter_magento_catalog:
    path: ../flutter_magento_catalog
  flutter_magento_cart:
    path: ../flutter_magento_cart
  flutter_magento_profile:
    path: ../flutter_magento_profile
  flutter_riverpod: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
